#!/bin/bash

# Setup
cd "$(dirname "$0")"
mkdir -p tmp
rm -rf bin/*
mkdir -p bin
# C program for getting the environment variable
gcc -o bin/variable_check support/variable_check.c
gcc -o bin/output_stderr support/output_stderr.c
gcc -o bin/output_stdout support/output_stdout.c
gcc -o bin/output_both support/output_both.c


# Load all files in support
for file in support/*.sh ; do
  source "$file"
done

LESSONS_TOTAL=$(find src -maxdepth 1 -name '*.sh' | wc -l)
LESSONS_LEFT=${LESSONS_TOTAL}
KOANS_TOTAL=$(grep --no-filename --count --perl-regexp "test_\w*\s*\(\)\s*{" src/*.sh | awk '{x+=$1} END {print x}')
KOANS_LEFT=${KOANS_TOTAL}

# Load all files in src
for file in src/*.sh ; do
  # echo "Thinking $(basename $file .sh)"
  source "$file"

  # OMG this is a bash test runner!! <3 <3 <3
  # functions=$(declare -F | cut -d ' ' -f 3 | grep ^test_)
  # This style allows us to run tests in order
  functions=$(grep -h test_ "$file" | cut -d '(' -f 1)
  for i in $functions ; do
    rm -rf tmp/*
    $i
    green "  $i has expanded your awareness."
    ((KOANS_LEFT -= 1))
  done
  ((LESSONS_LEFT -= 1))
done

