#!/bin/bash

# Setup
cd "$(dirname "$0")"
mkdir -p tmp
rm -rf bin/*
mkdir -p bin
# C program for getting the environment variable
gcc -o bin/variable_check support/variable_check.c
gcc -o bin/output_stderr support/output_stderr.c
gcc -o bin/output_stdout support/output_stdout.c
gcc -o bin/output_both support/output_both.c


# Load all files in support
for file in `ls support | grep .sh`; do
  source support/$file
done

# Load all files in src
for file in `ls src | grep .sh`; do
  source src/$file

  # OMG this is a bash test runner!! <3 <3 <3
  # functions=`declare -F | cut -d ' ' -f 3 | grep ^test_`
  # This style allows us to run tests in order
  functions=`grep -h test_ src/$file | cut -d '(' -f 1`
  for i in $functions; do
    rm -rf tmp/*
    $i
    green "  $i"
  done

done

