#!/usr/bin/env bash

# Setup
cd "$(dirname "$0")"
mkdir -p tmp

# Load all files in support
for file in support/*.sh ; do
  source "$file"
done

green() {
  return
}

# Load all files in src
for file in src/*.sh ; do
  source "$file"
done

$1

