#!/bin/bash

# Setup
cd "$(dirname "$0")"
mkdir -p tmp
rm -rf bin/*
mkdir -p bin
# C program for getting the environment variable
gcc -o bin/variable_check support/variable_check.c
gcc -o bin/output_stderr support/output_stderr.c
gcc -o bin/output_stdout support/output_stdout.c
gcc -o bin/output_both support/output_both.c


# Load all files in support
for file in support/*.sh ; do
  source "$file"
done

green() {
  return
}

# Load all files in src
for file in src/*.sh ; do
  source "$file"
done

$1

